name: CLI app action

description: 'Run your CLI app with ease'

branding:
  icon: 'clipboard'
  color: 'blue'

inputs:
  version:
    description: 'The version of the CLI app to download and use.'
    default: ${{ github.action_ref }}
    required: true

  arguments:
    description: 'The command-line arguments to be passed to CLI application.'
    default: 'hello'
    required: true

  working-directory:
    required: true
    default: ${{ github.workspace }}
    description: 'The directory to change into.'

  setup-java:
    default: 'true'
    description: 'Setup internal Java runtime.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup GraalVM 22.3.0'
      uses: graalvm/setup-graalvm@v1
      if: ${{ inputs.setup-java == 'true' }}
      with:
        version: '22.3.0'
        java-version: '17'
    - name: 'Download the specified CLI app'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ github.action_path }}/download-cli-tool.sh ${{ inputs.version }}
        java -jar cli-app.jar --version
    - name: 'Execute the CLI application'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Executing 'java -jar cli-app.jar ${{ inputs.arguments }}'"
        java -jar cli-app.jar ${{ inputs.arguments }}